### ISSUE TITLE
ARM checks fail

### ISSUE THREAD

**Issue by ggardet** [openSUSE/libstorage-ng#440]
armv7l and armv6l fails in OBS: https://build.opensuse.org/package/show/openSUSE:Factory:ARM/libstorage-ng
Because humanstring.test fails in 'make  check-TESTS'.

**Comment by ggardet** [comment]
Here is the testsuite/Utils/humanstring.log:
`Running 4 test cases...
humanstring.cc(139): error: in "test_big_numbers": check test("en_GB.UTF-8", 16 * EiB - 1 * B, true, 2, true) == "16.00 EiB" has failed [16 EiB != 16.00 EiB] 
humanstring.cc(143): error: in "test_big_numbers": exception OverflowException expected but not raised
humanstring.cc(144): error: in "test_big_numbers": exception OverflowException expected but not raised

*** 3 failures are detected in the test module "libstorage"
FAIL humanstring.test (exit status: 201)
`

**Comment by ggardet** [comment]
For the record: Bugzilla opened here: https://bugzilla.suse.com/show_bug.cgi?id=1078997

**Comment by aschnell** [comment]
Fixed by https://github.com/openSUSE/libstorage-ng/pull/459.
