### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [openSUSE/libstorage-ng#766]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [Btrfs::Impl](https://github.com/openSUSE/libstorage-ng/blob/0cae3730f86418d849a58fa1a51218920efb15c3/storage/Filesystems/BtrfsImpl.cc#L87 "Destructor for Btrfs::Impl")
- [CommentedConfigFile::remove](https://github.com/openSUSE/libstorage-ng/blob/e73193c966778d63203d62f1a6efaeb75c9ed11a/storage/Utils/CommentedConfigFile.cc#L88 "CommentedConfigFile::remove function")

**Comment by aschnell** [comment]
Thanks, I have removed the checks.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/openSUSE/libstorage-ng/commit/58598dce86a8ed7614664f76a975090ba27a9cac "Deletion of two redundant checks").
