### ISSUE TITLE
Non-NFS fstab entries detected as NFS

### ISSUE THREAD

**Issue by tacerus** [openSUSE/libstorage-ng#864]
Hi,

Currently, `libstorage-ng` seems to pick up other types of entries like `glusterfs` when checking for NFS entries, for example one like this:
`172.16.10.2:/psyched                     /mnt/gluster01       glusterfs defaults,_netdev   0  0`

Whilst I originally thought the `vfstype` field would be checked to only include entries containing `nfs` or `nfsv4`, it seems to actually be only considering the syntax of the first column (which in case of `glusterfs` is the same as it would be for `nfs`).

The issue mainly becomes apparent with software like YaST picking up and overriding unrelated entries (for example it would not only falsely show the user the `glusterfs` entry as a valid editable NFS share, but also override my `glusterfs` fstab entry with `nfs` upon saving NFS changes).

Is my assumption correct, that the NFS map is generated based on the syntax of the first column? Unfortunately I could not quite make out how the parsing works, otherwise I would have tried to solve it, as it seems relatively simple.

Maybe this could be considered for a future patch?

Best,
Georg

**Comment by aschnell** [comment]
You are right, the vfstype field is not used, see https://github.com/openSUSE/libstorage-ng/blob/master/storage/Filesystems/NfsImpl.cc#L130.

Checking for nfs and nfs4 is easy. But what about auto? Nfs works with auto. Does glusterfs work with auto?

**Comment by tacerus** [comment]
Hi @aschnell! 

Yes, [GlusterFS documentation](https://docs.gluster.org/en/latest/Administrator-Guide/Setting-Up-Clients/) does suggest mounting with `defaults`, which according to `fstab(5)` includes `auto`.

How is it an issue though, can the mounting options for non-nfs mounts not be arbitrary and unrelated to the vfstype, or are you suggesting to include glusterfs as an officially supported vfstype in order to check for its mount options?

**Comment by aschnell** [comment]
Sorry, I mean vfstype=auto.

**Comment by tacerus** [comment]
Oh! I am not sure about that, however I don't think so, because GlusterFS volumes support being mounted using one of two vfstype's - the FUSE based `glusterfs`, as well as `nfs`. The user should likely choose which one of the two they prefer.

**Comment by aschnell** [comment]
So for vfstype=auto we can assume it is a NFS mount?

**Comment by tacerus** [comment]
I did not find documentation on it, but upon testing it out, it does seem to default to `nfs` with vfstype=auto. However, I'm not sure it's a good idea to rely on it, as NFS based GlusterFS does not always work automatically (I think it requires some additional server-side dependencies because it uses Ganesha):

```
# mount 172.168.10.2:/psyched /mnt/temp
mount.nfs: requested NFS version or transport protocol is not supported
# mount -t nfs 172.168.10.2:/psyched /mnt/temp
mount.nfs: requested NFS version or transport protocol is not supported
```

**Comment by tacerus** [comment]
I understand. I think it's fine to treat vfstype=auto as NFS given my tests without `-t` (which is equivalent to using vfstype=auto in fstab) defaulted to `nfs`, but I'm not 100% certain if there are other conditions `mount` considers.

However checking for NFS, NFS4 and AUTO is I think reasonable enough - as it will not be worse than it is now (we'll be preventing vfstypes like `glusterfs` from showing up as NFS, but we're not excluding any NFS ones, which are the main focus of the function, and should only be installed by the user and software as either one of NFS/NFS4/AUTO in the first place).

Hope I got that right?

I am not an expert C++ programmer, but I wanted to try figuring it out (thanks for linking the relevant line above!). Do you mind giving me feedback on this? Is it PR-worthy? :-)

https://github.com/tacerus/libstorage-ng/commit/eeb171b8118a0798685f94d0c47832859d3a617f

The unit tests succeed, and I gave it a practical test using YaST's NFS client module with the following /etc/fstab sample:

```
192.168.5.5:/gluster              /mnt/gluster  glusterfs  defaults  0  0
192.168.5.5:/mnt/WD01             /mnt/nfs01  nfs        defaults  0  0
192.168.5.5:/mnt/WD01/isostore    /mnt/nfs02  nfs        defaults  0  0
```


Without the patch, it returns the bogus NFS entry:
![image](https://user-images.githubusercontent.com/5121046/160169947-47806c4c-2c03-4d46-b479-79fae9f28fe5.png)

With the patch, it is correctly omitted:
![image](https://user-images.githubusercontent.com/5121046/160169973-c7ea57f8-77d2-4033-9eed-3b1925b9f0d7.png)

**Comment by aschnell** [comment]
Thanks for the report and patch.

**Comment by tacerus** [comment]
Thanks for helping me with it! :-)
